# Generated by Django 4.2.7 on 2024-10-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='вопрос для голосования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('sent', models.BooleanField(default=False)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'голосование',
                'verbose_name_plural': 'голосования',
            },
        ),
        migrations.CreateModel(
            name='ProfileVideoNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='videos', verbose_name='кружок пользователя')),
                ('file_id', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата отправки')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('sent', 'Sent')], default='waiting', max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_video_notes', to='user_profile.profile')),
            ],
            options={
                'verbose_name': 'Кружок пользователя',
                'verbose_name_plural': 'Кружки пользователей',
            },
        ),
        migrations.CreateModel(
            name='PublicVideoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата отправки')),
                ('profile_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_from_messages', to='user_profile.profile')),
                ('profile_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_to', to='user_profile.profile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_messages', to='core.profilevideonote')),
            ],
            options={
                'verbose_name': 'Публичные кружочки',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='текст')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='core.poll', verbose_name='вопрос для голосвания')),
            ],
            options={
                'verbose_name': 'Опция голосования',
                'verbose_name_plural': 'Опции голосований',
            },
        ),
    ]
